// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Selin_Robert_Cristian.Data;

#nullable disable

namespace Proiect_Selin_Robert_Cristian.Migrations
{
    [DbContext(typeof(Proiect_Selin_Robert_CristianContext))]
    [Migration("20230112112557_SportsFieldType")]
    partial class SportsFieldType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.SportsFacility", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportsFacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SportsFacility");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.SportsField", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Field_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price_Per_Hour")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int?>("SportsFacilityID")
                        .HasColumnType("int");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SportsFacilityID");

                    b.ToTable("SportsField");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.SportsFieldType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("SportsFieldID")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SportsFieldID");

                    b.HasIndex("TypeID");

                    b.ToTable("SportsFieldType");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.SportsField", b =>
                {
                    b.HasOne("Proiect_Selin_Robert_Cristian.Models.SportsFacility", "SportsFacility")
                        .WithMany("SportsFields")
                        .HasForeignKey("SportsFacilityID");

                    b.Navigation("SportsFacility");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.SportsFieldType", b =>
                {
                    b.HasOne("Proiect_Selin_Robert_Cristian.Models.SportsField", "SportsField")
                        .WithMany("SportsFieldTypes")
                        .HasForeignKey("SportsFieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Selin_Robert_Cristian.Models.Type", "Type")
                        .WithMany("SportsFieldTypes")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportsField");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.SportsFacility", b =>
                {
                    b.Navigation("SportsFields");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.SportsField", b =>
                {
                    b.Navigation("SportsFieldTypes");
                });

            modelBuilder.Entity("Proiect_Selin_Robert_Cristian.Models.Type", b =>
                {
                    b.Navigation("SportsFieldTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
